# Generated by Django 3.0.6 on 2020-11-28 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='teacherData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=200)),
                ('Education', models.CharField(max_length=400)),
                ('facebook_id', models.SlugField(max_length=400)),
                ('instagram_id', models.SlugField(max_length=400)),
                ('email_id', models.SlugField(max_length=400)),
                ('tag_line', models.CharField(max_length=400)),
            ],
        ),
    ]
