# Generated by Django 3.0.6 on 2020-11-30 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=300)),
                ('course_id', models.IntegerField()),
                ('course_info', models.TextField()),
                ('cover_image_url', models.SlugField()),
                ('videos_location', models.SlugField()),
                ('instructor_name', models.CharField(max_length=300)),
                ('course_slug', models.SlugField(default='course')),
                ('course_thumbnail', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor_name', models.CharField(max_length=300)),
                ('instructor_tagline', models.TextField()),
                ('instructor_img', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='tutorials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutorial_name', models.CharField(max_length=300)),
                ('tutorial_description', models.TextField()),
                ('tutorial_slug', models.SlugField(default='tut')),
                ('tutorial_video', models.FileField(blank=True, upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='course_reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name', models.CharField(max_length=300)),
                ('review_para', models.TextField()),
                ('review_rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('course_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='content.course')),
            ],
        ),
    ]
