# Generated by Django 3.0.6 on 2020-10-11 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='review_para',
        ),
        migrations.RemoveField(
            model_name='course',
            name='review_rating',
        ),
        migrations.RemoveField(
            model_name='course',
            name='reviewer_name',
        ),
        migrations.CreateModel(
            name='course_reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name', models.CharField(max_length=300)),
                ('review_para', models.TextField()),
                ('review_rating', models.IntegerField()),
                ('course_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='content.course')),
            ],
        ),
    ]
