# Generated by Django 3.0.6 on 2020-11-30 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_tutorials_course_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorials',
            name='tutorial_video',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
