# Generated by Django 3.0.6 on 2020-10-11 03:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20201011_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_reviews',
            name='review_rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
