# Generated by Django 3.0.6 on 2020-11-30 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20201130_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorials',
            name='tutorial_video',
            field=models.FileField(upload_to=''),
        ),
    ]
