# Generated by Django 3.0.6 on 2020-11-30 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_auto_20201130_1937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='cover_image_url',
        ),
        migrations.RemoveField(
            model_name='course',
            name='videos_location',
        ),
    ]
