# Generated by Django 3.0.6 on 2020-10-11 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_auto_20201011_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_reviews',
            name='review_rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
    ]
