# Generated by Django 3.0.6 on 2021-05-28 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_auto_20201130_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_reviews',
            name='reviewer_img',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
