# Generated by Django 3.0.6 on 2021-05-28 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_course_reviews_slide'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_reviews',
            name='reviewer_about',
            field=models.CharField(default=2, max_length=600),
            preserve_default=False,
        ),
    ]
