# Generated by Django 3.0.6 on 2021-05-28 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_course_reviews_reviewer_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='completion_time',
            field=models.CharField(default=5, max_length=50),
            preserve_default=False,
        ),
    ]
