# Generated by Django 3.0.6 on 2021-03-22 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_no', models.IntegerField()),
                ('q1', models.TextField()),
                ('q1o1', models.TextField()),
                ('q1o2', models.TextField()),
                ('q1o3', models.TextField()),
                ('q1o4', models.TextField()),
                ('q2', models.TextField()),
                ('q2o1', models.TextField()),
                ('q2o2', models.TextField()),
                ('q2o3', models.TextField()),
                ('q2o4', models.TextField()),
                ('q3', models.TextField()),
                ('q3o1', models.TextField()),
                ('q3o2', models.TextField()),
                ('q3o3', models.TextField()),
                ('q3o4', models.TextField()),
                ('q4', models.TextField()),
                ('q4o1', models.TextField()),
                ('q4o2', models.TextField()),
                ('q4o3', models.TextField()),
                ('q4o4', models.TextField()),
                ('q5', models.TextField()),
                ('q5o1', models.TextField()),
                ('q5o2', models.TextField()),
                ('q5o3', models.TextField()),
                ('q5o4', models.TextField()),
                ('q6', models.TextField()),
                ('q6o1', models.TextField()),
                ('q6o2', models.TextField()),
                ('q6o3', models.TextField()),
                ('q6o4', models.TextField()),
                ('q7', models.TextField()),
                ('q7o1', models.TextField()),
                ('q7o2', models.TextField()),
                ('q7o3', models.TextField()),
                ('q7o4', models.TextField()),
                ('q8', models.TextField()),
                ('q8o1', models.TextField()),
                ('q8o2', models.TextField()),
                ('q8o3', models.TextField()),
                ('q8o4', models.TextField()),
                ('q9', models.TextField()),
                ('q9o1', models.TextField()),
                ('q9o2', models.TextField()),
                ('q9o3', models.TextField()),
                ('q9o4', models.TextField()),
                ('q10', models.TextField()),
                ('q10o1', models.TextField()),
                ('q10o2', models.TextField()),
                ('q10o3', models.TextField()),
                ('q10o4', models.TextField()),
            ],
        ),
    ]
