# Generated by Django 3.0.6 on 2021-03-26 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_question_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answer',
        ),
    ]
