# Generated by Django 3.0.6 on 2021-04-01 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_question_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='quiz_slug',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
