# Generated by Django 3.0.6 on 2021-03-30 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_details',
            name='branch',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='student_details',
            name='college',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='student_details',
            name='courses',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='student_details',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='student_details',
            name='email',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='student_details',
            name='phone',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='student_details',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
