# Generated by Django 3.0.6 on 2021-03-30 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20210330_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz_scores',
            name='score',
            field=models.IntegerField(null=True),
        ),
    ]
