# Generated by Django 3.0.6 on 2021-03-31 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20210330_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_details',
            name='name',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
