# Generated by Django 3.0.6 on 2021-03-31 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_student_details_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_details',
            name='courses',
            field=models.TextField(blank=True, null=True),
        ),
    ]
