# Generated by Django 3.0.6 on 2021-03-31 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_auto_20201130_2201'),
        ('dashboard', '0005_auto_20210331_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses_enrolled',
            name='course_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='content.course'),
        ),
    ]
